name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        github-token: ${{ github.token }}
  
    - name: Test
      run: go test -v ./...
      
    - name: Go report card
      uses: creekorful/goreportcard-action@v1.0
    
    - name: go-mnd
      uses: tommy-muehle/go-mnd@v2.2.0
      with:
        args: -h
        
    
